version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: todo_postgres
    restart: always
    environment:
      POSTGRES_DB: todo_list
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  web:
    build: .
    container_name: todo_django
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:admin@host.docker.internal:5432/todo_list
    ports:
      - "8000:8000"
    command: >
      python manage.py runserver 0.0.0.0:8000


volumes:
  postgres_data:
