version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: todo_postgres
    restart: always
    environment:
      POSTGRES_DB: testing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: todo_django
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:admin@db:5432/testing
    ports:
      - "8000:8000"
    command: >
      sh -c "sleep 10 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:
